import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-highest": "#d5e3fd",
        "on-secondary-container": "#fffbff",
        "inverse-primary": "#bcc7de",
        "on-primary-container": "#8590a6",
        "outline": "#75777d",
        "secondary": "#1d4ed8",
        "tertiary-container": "#003013",
        "on-background": "#0d1c2f",
        "inverse-surface": "#233144",
        "tertiary": "#001907",
        "surface": "#f8f9ff",
        "on-secondary": "#ffffff",
        "surface-variant": "#d5e3fd",
        "tertiary-fixed-dim": "#8bd79b",
        "tertiary-fixed": "#a6f4b5",
        "on-tertiary": "#ffffff",
        "surface-container-low": "#eff4ff",
        "outline-variant": "#c5c6cd",
        "on-surface": "#0d1c2f",
        "on-tertiary-container": "#559f67",
        "surface-bright": "#f8f9ff",
        "error": "#ba1a1a",
        "on-tertiary-fixed-variant": "#005226",
        "primary-container": "#1e293b",
        "on-surface-variant": "#45474c",
        "surface-container": "#e6eeff",
        "secondary-container": "#4069f2",
        "primary-fixed": "#d8e3fb",
        "on-error-container": "#93000a",
        "on-error": "#ffffff",
        "surface-container-high": "#dde9ff",
        "surface-tint": "#545f73",
        "on-secondary-fixed": "#001551",
        "secondary-fixed": "#dce1ff",
        "primary": "#091426",
        "on-primary": "#ffffff",
        "on-primary-fixed": "#111c2d",
        "secondary-fixed-dim": "#b7c4ff",
        "on-secondary-fixed-variant": "#0039b5",
        "error-container": "#ffdad6",
        "primary-fixed-dim": "#bcc7de",
        "on-tertiary-fixed": "#00210b",
        "surface-dim": "#ccdbf4",
        "background": "#f8f9ff",
        "inverse-on-surface": "#ebf1ff",
        "surface-container-lowest": "#ffffff",
        "on-primary-fixed-variant": "#3c475a"
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem"
      },
      spacing: {
        "touch-cushion": "8px",
        "space-xs": "0.5rem",
        "space-lg": "1.5rem",
        "margin-desktop": "2rem",
        "space-2xs": "0.25rem",
        "target-min": "44px",
        "space-md": "1rem",
        "gutter-mobile": "1rem",
        "space-xl": "2rem",
        "margin-mobile": "1rem",
        "space-2xl": "3rem",
        "gutter-desktop": "1.5rem",
        "space-sm": "0.75rem"
      },
      fontFamily: {
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "body-bold": ["Inter", "sans-serif"],
        "display": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-sm": ["Inter", "sans-serif"],
        "display-mobile": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"]
      },
      fontSize: {
        "headline-lg-mobile": ["26px", { lineHeight: "36px", letterSpacing: "0em", fontWeight: "700" }],
        "label-md": ["14px", { lineHeight: "22px", letterSpacing: "0.01em", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "36px", letterSpacing: "0em", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "44px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "body-bold": ["16px", { lineHeight: "26px", letterSpacing: "0em", fontWeight: "600" }],
        "display": ["40px", { lineHeight: "52px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-sm": ["13px", { lineHeight: "20px", letterSpacing: "0.02em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", letterSpacing: "0em", fontWeight: "400" }],
        "headline-sm": ["20px", { lineHeight: "30px", letterSpacing: "0em", fontWeight: "600" }],
        "display-mobile": ["30px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "26px", letterSpacing: "0em", fontWeight: "400" }]
      }
    },
  },
  plugins: [],
};
export default config;
